#!/bin/sh

set -Ceu

SCRIPTS="`dirname -- "$0"`"

sudo -u probcomp-acme "$SCRIPTS"/renew.unpriv
if nginx -t >/dev/null 2>&1; then
    service nginx reload
else
    nginx -t
fi 2>&1 >/dev/null | logger -t probcomp-acme -p daemon.error
