#!/bin/sh

set -Ceu

# Script to set up the static administrivia of acme for probcomp-N.
# This does not generate an account key or create a cron job.  Written
# by Riastradh 20161010.

progname="`basename -- "$0"`"
SCRIPTS="`dirname -- "$0"`"

if [ $# -ne 1 ]; then
    printf >&2 'Usage: %s <domain>\n' "$progname"
    exit 1
fi

domain="$1"

mkdir -m 700 /etc/acme

ok=

clean ()
{
    if [ -n "$ok" ]; then return; fi
    rmdir /var/lib/acme/certs
    rmdir /var/lib/acme/challenges
    deluser --system acme	# also deletes group
    rmdir /var/lib/acme
    rm /etc/acme/domain.key
    rm /etc/acme/domain.csr
    rm /etc/acme/domain.crt
    rmdir /etc/acme
}

trap clean EXIT HUP INT TERM

adduser --system --group --home /var/lib/acme acme

mkdir /var/lib/acme/certs
mkdir /var/lib/acme/challenges
chown -R acme:acme /var/lib/acme

"$SCRIPTS"/gendomain -d "$domain" -k /etc/acme/domain.key \
    -r /etc/acme/domain.csr
chmod 640 /etc/acme/domain.key /etc/acme/domain.csr
chgrp acme /etc/acme/domain.key /etc/acme/domain.csr

ln -s /var/lib/acme/certs/chain.pem /etc/acme/domain.crt

chmod 750 /etc/acme
chgrp acme /etc/acme

ok=1
