#!/bin/sh

set -Ceu

# Script to set up the static administrivia of acme for probcomp-N.
# This does not generate an account key or create a cron job.  Written
# by Riastradh 20161010.

progname="`basename -- "$0"`"
SCRIPTS="`dirname -- "$0"`"

if [ $# -ne 1 ]; then
    printf >&2 'Usage: %s <domain>\n' "$progname"
    exit 1
fi

domain="$1"

mkdir -m 700 /etc/probcomp-acme

ok=

clean ()
{
    if [ -n "$ok" ]; then return; fi
    rmdir /var/lib/probcomp-acme/certs
    rmdir /var/lib/probcomp-acme/challenges
    deluser --system probcomp-acme      # also deletes group
    rmdir /var/lib/probcomp-acme
    rm -f /etc/probcomp-acme/domain.key || :
    rm -f /etc/probcomp-acme/domain.csr || :
    rm -f /etc/probcomp-acme/domain.crt || :
    rmdir /etc/probcomp-acme
}

trap clean EXIT HUP INT TERM

adduser --system --group --home /var/lib/probcomp-acme probcomp-acme

mkdir /var/lib/probcomp-acme/certs
mkdir /var/lib/probcomp-acme/challenges
chown -R probcomp-acme:probcomp-acme /var/lib/probcomp-acme

"$SCRIPTS"/gendomain -d "$domain" -k /etc/probcomp-acme/domain.key \
    -r /etc/probcomp-acme/domain.csr
chmod 640 /etc/probcomp-acme/domain.key /etc/probcomp-acme/domain.csr
chgrp probcomp-acme /etc/probcomp-acme/domain.key /etc/probcomp-acme/domain.csr

ln -s /var/lib/probcomp-acme/certs/chain.pem /etc/probcomp-acme/domain.crt

chmod 750 /etc/probcomp-acme
chgrp probcomp-acme /etc/probcomp-acme

ok=1
